import string
import random

search_10 = "TokyoJapan"
search_100 = "KeioUniversityisaleadingresearchuniversitycommittedtoexcellenceandinnovationineducation,researchandm"
search_1000 = "SpaceExplorationTechnologiesCorp.,tradingasSpaceX,isanAmericanaerospacemanufacturerandspacetransportationservicescompanyheadquarteredinHawthorne,California.Itwasfoundedin2002byElonMuskwiththegoalofreducingspacetransportationcoststoenablethecolonizationofMars.[8][9][10]SpaceXhasdevelopedseverallaunchvehiclesandtheDragonspacecraft.SpaceX'sachievementsincludethefirstprivatelyfundedliquid-propellantrockettoreachorbit(Falcon1in2008),[11]thefirstprivatecompanytosuccessfullylaunch,orbit,andrecoveraspacecraft(Dragonin2010),thefirstprivatecompanytosendaspacecrafttotheInternationalSpaceStation(Dragonin2012),[12]thefirstpropulsivelandingforanorbitalrocket(Falcon9in2015),thefirstreuseofanorbitalrocket(Falcon9in2017),thefirstprivatecompanytolaunchanobjectintoorbitaroundtheSun(FalconHeavy'spayloadofaTeslaRoadsterin2018),andthefirstprivatecompanytosendastronautstotheInternationalSpaceStation(Dragon2in2020).[13]SpaceXhasflown20[14]resupplymissionstotheInternationalSpaceStation(ISS)underapartnershipwit"
search_10000 = "TheAsgardianLokiencounterstheOther,theleaderofanextraterrestrialraceknownastheChitauri.InexchangeforretrievingtheTesseract,[N2]apowerfulenergysourceofunknownpotential,theOtherpromisesLokianarmywithwhichhecansubjugateEarth.NickFury,directoroftheespionageagencyS.H.I.E.L.D.,andhislieutenantAgentMariaHillarriveataremoteresearchfacilityduringanevacuation,wherephysicistDr.ErikSelvigisleadingaresearchteamexperimentingontheTesseract.AgentPhilCoulsonexplainsthattheobjecthasbegunradiatinganunusualformofenergy.TheTesseractsuddenlyactivatesandopensawormhole,allowingLokitoreachEarth.LokitakestheTesseractanduseshissceptertoenslaveSelvigandafewotheragents,includingClintBarton,toaidhiminhisgetaway.Inresponsetotheattack,FuryreactivatestheAvengersInitiative.AgentNatashaRomanoffissenttoKolkatatorecruitDr.BruceBannertotracetheTesseractthroughitsgammaradiationemissions.CoulsonvisitsTonyStarktohavehimreviewSelvig'sresearch,andFuryapproachesSteveRogerswithanassignmenttoretrievetheTesseract.InStuttgart,BartonstealsiridiumneededtostabilizetheTesseract'spowerwhileLokicausesadistraction,leadingtoabriefconfrontationwithRogers,Stark,andRomanoffthatendswithLoki'ssurrender.WhileLokiisbeingescortedtoS.H.I.E.L.D.,Thor,hisadoptivebrother,arrivesandfreeshim,hopingtoconvincehimtoabandonhisplanandreturntoAsgard.AfteraconfrontationwithStarkandRogers,ThoragreestotakeLokitoS.H.I.E.L.D.'sflyingaircraftcarrier,theHelicarrier.Uponarrival,LokiisimprisonedwhileBannerandStarkattempttolocatetheTesseract.TheAvengersbecomedivided,bothoverhowtoapproachLokiandtherevelationthatS.H.I.E.L.D.planstoharnesstheTesseracttodevelopweaponsasadeterrentagainsthostileextraterrestrials.Asthegroupargues,BartonandLoki'sotherpossessedagentsattacktheHelicarrier,disablingoneofitsenginesinflightandcausingBannertotransformintotheHulk.StarkandRogersworktorestartthedamagedengine,andThorattemptstostoptheHulk'srampage.RomanoffreluctantlyfightsBarton,andknockshimunconscious,breakingLoki'smindcontrol.LokiescapesafterkillingCoulsonandejectingThorfromtheairship,whiletheHulkfallstothegroundafterattackingaS.H.I.E.L.D.fighterjet.FuryusesCoulson'sdeathtomotivatetheAvengersintoworkingasateam.StarkandRogersrealizethatforLoki,simplydefeatingthemwillnotbeenough;heneedstooverpowerthempubliclytovalidatehimselfasrulerofEarth.LokiusestheTesseract,inconjunctionwithadeviceSelvigbuilt,toopenawormholeaboveStarkTowertotheChitaurifleetinspace,launchinghisinvasion.Rogers,Stark,Romanoff,Barton,andThorrallyindefenseofNewYorkCity,thewormhole'slocation.BannerarrivesandtransformsintotheHulk,andtogethertheAvengersbattletheChitauriwhileevacuatingcivilians.TheHulkfindsLokiandbeatshimintosubmission.Romanoffmakesherwaytothewormholegenerator,whereSelvig,freedfromLoki'smindcontrol,revealsthatLoki'ssceptercanbeusedtoshutdownthegenerator.Meanwhile,Fury'ssuperiorsfromtheWorldSecurityCouncilattempttoendtheinvasionbylaunchinganuclearmissileatMidtownManhattan.StarkinterceptsthemissileandtakesitthroughthewormholetowardtheChitaurifleet.Themissiledetonates,destroyingtheChitaurimothershipanddisablingtheirforcesonEarth.Stark'ssuitlosespower,andhefallsbackthroughthewormholejustasRomanoffclosesit.Starkgoesintofreefall,buttheHulksaveshimfromcrashingintotheground.Intheaftermath,ThorreturnsLokiandtheTesseracttoAsgard,whileFuryexpressesconfidencethattheAvengerswillreturnifandwhentheyareneeded.Inamid-creditsscene,theOtherconferswithhismaster[N3]aboutthefailedattackonEarth.IntheEasternEuropeancountryofSokovia,theAvengers-TonyStark,SteveRogers,Thor,BruceBanner,NatashaRomanoff,andClintBarton-raidaHydrafacilitycommandedbyBaronWolfgangvonStrucker,whohasbeenexperimentingonhumansusingthescepterpreviouslywieldedbyLoki.TheyencountertwoofStrucker'stestsubjects-twinsPietro,whohassuperhumanspeed,andWandaMaximoff,whohastelepathicandtelekineticabilities-andapprehendStrucker,whileStarkretrievesLoki'sscepter.StarkandBannerdiscoveranartificialintelligencewithinthescepter'sgem,andsecretlydecidetouseittocompleteStark'sUltronglobaldefenseprogram.TheunexpectedlysentientUltron,believinghemusteradicatehumanitytosaveEarth,eliminatesStark'sA.I.J.A.R.V.I.S.andattackstheAvengersattheirheadquarters.Escapingwiththescepter,UltronusestheresourcesinStrucker'sSokoviabasetoupgradehisrudimentarybodyandbuildanarmyofrobotdrones.HavingkilledStrucker,herecruitstheMaximoffs,whoholdStarkresponsiblefortheirparents'deathsbyhiscompany'sweapons,andgoestothebaseofarmsdealerUlyssesKlaueinJohannesburgtoobtainWakandanvibranium.TheAvengersattackUltronandtheMaximoffs,butWandasubduesthemwithhauntingvisions,causingBannertoturnintotheHulkandrampageuntilStarkstopshimwithhisanti-Hulkarmor.[N1]Aworldwidebacklashovertheresultingdestruction,andthefearsWanda'shallucinationsincited,sendtheteamintohidingatasafehouse.ThordepartstoconsultwithDr.ErikSelvigontheapocalypticfuturehesawinhishallucination,whileNickFuryarrivesandencouragestheteamtoformaplantostopUltron.InSeoul,UltronusesLoki'ssceptertoenslavetheteam'sfriendDr.HelenCho.Theyusehersynthetic-tissuetechnology,vibranium,andthescepter'sgemtocraftanewbody.AsUltronuploadshimselfintothebody,Wandaisabletoreadhismind;discoveringhisplanforhumanextinction,theMaximoffsturnagainstUltron.Rogers,Romanoff,andBartonfindUltronandretrievethesyntheticbody,butUltroncapturesRomanoff.TheAvengersfightamongstthemselveswhenStarkandBannersecretlyuploadJ.A.R.V.I.S.-whoisstilloperationalafterhidingfromUltroninsidetheInternet-intothesyntheticbody.Thorreturnstohelpactivatethebody,explainingbasedonhisvisionthatthegemonitsbrowistheMindStone,oneofthesixInfinityStones,themostpowerfulobjectsinexistence.ThisVisionandtheMaximoffsaccompanytheAvengerstoSokovia,whereUltronhasusedtheremainingvibraniumtobuildamachinetoliftalargepartofthecapitalcityskyward,intendingtocrashitintothegroundtocauseglobalextinction.BannerrescuesRomanoff,whoawakenstheHulkforthebattle.TheAvengersfightUltron'sarmywhileFuryarrivesinaHelicarrierwithMariaHill,JamesRhodesandS.H.I.E.L.D.agentstoevacuatecivilians.PietrodieswhenheshieldsBartonfromgunfire,andavengefulWandaabandonsherposttodestroyUltron'sprimarybody,whichallowsoneofhisdronestoactivatethemachine.Thecityplummets,butStarkandThoroverloadthemachineandshatterthelandmass.Intheaftermath,theHulk,unwillingtoendangerRomanoffbybeingwithher,departsinaQuinjet,whileVisionconfrontsandseeminglydestroysUltron'slastremainingbody.Later,withtheAvengershavingestablishedanewbaserunbyFury,Hill,Cho,andSelvig,ThorreturnstoAsgardtolearnmoreabouttheforceshesuspectshavemanipulatedrecentevents.AsStarkleavesandBartonretires,RogersandRomanoffpreparetotrainnewAvengers:Rhodes,Vision,SamWilson,andWanda.Inamid-creditsscene,Thanos,dissatisfiedbythefailuresofhispawns,donsagauntlet[N2]andvowstoretrievetheInfinityStoneshimself.HavingacquiredthePowerStone,oneofthesixInfinityStones,fromtheplanetXandar,Thanosandhislieutenants-EbonyMaw,CullObsidian,ProximaMidnight,andCorvusGlaive-interceptthespaceshipcarryingthesurvivorsofAsgard'srecentdestruction.[N1]AstheyextracttheSpaceStonefromtheTesseract,ThanossubduesThor,overpowersHulk,andkillsLoki.ThanosalsokillsHeimdallafterhesendsHulktoEarthusingtheBifrost.Thanosandhislieutenantsdepart,destroyingtheship.Hulkcrash-landsintheSanctumSanctoruminNewYorkCity,revertingtotheformofBruceBanner.HewarnsStephenStrangeandWongaboutThanos'plantokillhalfofalllifeintheuniverse,andtheyrecruitTonyStark.MawandObsidianarrivetoretrievetheTimeStonefromStrange,drawingtheattentionofPeterParker.MawisunabletotaketheTimeStoneduetoanenchantmentandcapturesStrangeinstead.StarkandParkersneakaboardMaw'sspaceshipwhileWongstaysbehindtoguardtheSanctum.InEdinburgh,MidnightandGlaiveambushWandaMaximoffandVisioninordertoretrievetheMindStone,whichisinVision'sforehead.SteveRogers,NatashaRomanoff,andSamWilsonrescuethemandtheytakeshelterwithJamesRhodesandBanneratAvengersCompound.VisionasksMaximofftodestroyhimselfandtheMindStonetokeepThanosfromretrievingit,butMaximoffrefuses.RogerssuggeststheytraveltoWakanda,whichhebelieveshastheresourcestoremovetheStonewithoutkillingVision.TheGuardiansoftheGalaxyrespondtoadistresscallfromtheAsgardianshipandrescueThor,whosurmisesthatThanosiscurrentlygoingaftertheRealityStone,whichisinthepossessionoftheCollectoronKnowhere.RocketandGrootaccompanyThortoNidavellir,wheretheyandEitricreateStormbreaker,abattle-axecapableofkillingThanos.OnKnowhere,PeterQuill,Gamora,Drax,andMantisfindThanoswiththeRealityStonealreadyinhispossession.ThanoskidnapsGamora,hisadopteddaughter,whorevealstheSoulStoneisonVormirinordertosavehercaptiveadoptedsister,Nebula,fromtorture.OnVormir,theStone'skeeper,RedSkull,tellsThanosthathecanonlyacquireitbysacrificingsomeoneheloves.ThanoskillsGamora,earningtheStone.NebulaescapescaptivityandaskstheremainingGuardianstomeetheratThanos'destroyedhomeworld,Titan.StarkandParkerkillMawandrescueStrange.LandingonTitan,theymeetQuill,Drax,andMantis.StrangeusestheTimeStonetoviewmillionsofpossiblefutures,seeingonlyoneinwhichThanosloses.ThegroupformsaplantosubdueThanosandremovetheInfinityGauntlet,whichheusestohousetheStones.Thanosappearsandjustifieshisplansasnecessarytoensurethesurvivalofauniversethreatenedbyoverpopulation.Nebulaarrivessoonafter,andhelpstheotherssubdueThanosuntilshededucesthatThanoshaskilledGamora.Enraged,QuillattacksThanos,allowinghimtobreakthegroup'sholdandoverpowerthem.StarkisseriouslywoundedbyThanos,butissparedafterStrangesurrenderstheTimeStonetoThanos.InWakanda,RogersreuniteswithBuckyBarnesbeforeThanos'armyinvades.TheAvengers,alongsideT'ChallaandtheWakandanforces,mountadefensewhileShuriworkstoextracttheMindStonefromVision.HulkrefusestofightafterlosingtoThanos,soBannerfightsinStark'sHulkbusterarmor.Thor,Rocket,andGrootarrivetoreinforcetheAvengers;Midnight,Obsidian,andGlaivearekilledandtheirarmyisrouted,butShuriisunabletocompletetheextractionoftheMindStonefromVisionbeforeThanosarrivestoretrieveit.MaximoffdestroystheMindStoneandVision,butThanosusestheTimeStonetoreverseheractions.HeripstherepairedMindStonefromVision'sforehead,killinghim.ThorseverelywoundsThanoswithStormbreaker,butThanosactivatesthecompletedGauntletbysnappinghisfingers.Hethenteleportsa"


def create_random(query: string, length: int):
	char_list = []
	for _ in range(length // 2):
		char_list.append(random.choice(string.ascii_letters))
	char_list.append(query)
	for _ in range(length // 2):
		char_list.append(random.choice(string.ascii_letters))
	data = ''.join(char_list)
	data = data[:length]
	file_name = "random_chars/" + str(length) + "-"+ str(len(query)) + ".txt"
	f = open(file_name, "w")
	f.write(data)
	f.close()

def create_missing_fisrt(query: string, length: int):
	missing_first = query[1:]
	char_list = []
	for _ in range((length // len(missing_first))// 2):
		char_list.append(missing_first)
	char_list.append(query)
	for _ in range((length // len(missing_first))// 2):
		char_list.append(missing_first)
	data = ''.join(char_list)
	data = data[:length]
	file_name = "first_missed/" + str(length) + "-"+ str(len(query)) + ".txt"
	f = open(file_name, "w")
	f.write(data)
	f.close()

def create_missing_last(query: string, length: int):
	missing_last = query[:-1]
	char_list = []
	for _ in range((length // len(missing_last))// 2):
		char_list.append(missing_last)
	char_list.append(query)
	for _ in range((length // len(missing_last))// 2):
		char_list.append(missing_last)
	data = ''.join(char_list)
	data = data[:length]
	file_name = "last_missed/" + str(length) + "-"+ str(len(query)) + ".txt"
	f = open(file_name, "w")
	f.write(data)
	f.close()

def create_missing_first_or_last(query: string, length: int):
	missing_first = query[1:]
	missing_last = query[:-1]
	char_list = []
	for _ in range((length // len(missing_last))// 4):
		char_list.append(missing_first)
		char_list.append(missing_last)
	char_list.append(query)
	for _ in range((length // len(missing_last))// 4):
		char_list.append(missing_first)
		char_list.append(missing_last)
	data = ''.join(char_list)
	data = data[:length]
	file_name = "either_missed/" + str(length) + "-"+ str(len(query)) + ".txt"
	f = open(file_name, "w")
	f.write(data)
	f.close()

def create_failure(length: int):
	char_list = []
	for _ in range(length):
		char_list.append(random.choice(string.ascii_letters))
	data = ''.join(char_list)
	file_name = "failure/" + str(length) + ".txt"
	f = open(file_name, "w")
	f.write(data)
	f.close()

queries = [search_10, search_100, search_1000, search_10000]
field_length = 100000
while field_length <= 10 ** 8: # less than or equal to 100M
	for q in queries:
		create_random(q, field_length)
		create_missing_fisrt(q, field_length)
		create_missing_last(q, field_length)
		create_missing_first_or_last(q, field_length)
	create_failure(field_length)
	field_length *= 10