list = list(range(10))
print(list)
print("list[1:3] ==", list[1:3])
print("list[:3] ==", list[:3])
print("list[1:] ==", list[1:])
print("list[-3:] ==", list[-3:])
print("list[:-3] ==", list[:-3])
print("list[:-1] ==", list[:-1])
print("list[::2] ==", list[::2])
print("list[::-1] ==", list[::-1])
print("list[::-2] ==", list[::-2])
print("list[3::3] ==", list[3::3])
